services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    # user: root
    ports:
      - "5678:5678"
    # entrypoint:
    #     - chown
    # command: -R node:node /home/node/.n8n
    volumes:
        - ~/.n8n:/home/node/.n8n
    # environment:
    #   - N8N_BASIC_AUTH_ACTIVE=true
    #   - N8N_PORT=5678
